### ISSUE TITLE
Allow syntax highlighting customization

### ISSUE THREAD

**Issue by KonerDev** [Xed-Editor/Xed-Editor#881]
The importable `theme.json` files should include the ability to change the syntax highlighting colors. It should provide full control over the colors used for different code elements (e.g., keywords, strings, comments, functions, and variables) as it is done in the default themes: https://github.com/Xed-Editor/Xed-Editor/blob/3b8c9abe9305993795e336327deb10e6d84d29c0/core/main/src/main/assets/textmate/quietlight.json#L1-L9

**Comment by KonerDev** [comment]
I like the structure of the `theme.json` files in Squircle CE:
https://github.com/massivemadness/Squircle-CE/blob/5a8df76287c00f8295bf0b4a26440738d686155d/feature-themes/impl/src/main/assets/themes/visual_studio.json

**Comment by RohitKushvaha01** [comment]
> I like the structure of the `theme.json` files in Squircle CE: https://github.com/massivemadness/Squircle-CE/blob/5a8df76287c00f8295bf0b4a26440738d686155d/feature-themes/impl/src/main/assets/themes/visual_studio.json

I've already implemented this to allow changing the color scheme:

[https://github.com/Xed-Editor/Theme-Template/blob/main/Theme.json](https://github.com/Xed-Editor/Theme-Template/blob/main/Theme.json)

but it has some minor issues with transparent colors.

**Comment by KonerDev** [comment]
> I've already implemented this to allow changing the color scheme:

@RohitKushvaha01 
But it's not working. It is still not possible to change the colors of different code elements like strings or comments. The only syntax colors I can change with the current implementation are these colors, but they don't seem to have any effect at the moment:

<img width="640" height="417" alt="Image" src="https://github.com/user-attachments/assets/87fa7cd5-6613-46c3-9376-b4329d4112ac" />
